version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: ai_pose_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ai_pose_gallery
      MYSQL_USER: aipose
      MYSQL_PASSWORD: aipose123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # 应用服务
  app:
    build: .
    container_name: ai_pose_app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/ai_pose_gallery
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=ai_pose_gallery
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: